// Generated by CoffeeScript 1.9.3
(function() {
  var Util;

  Util = (function() {
    function Util() {}

    Util.curry = function(orig_func) {
      var ap, args, fn;
      ap = Array.prototype;
      args = arguments;
      fn = function() {
        ap.push.apply(fn.args, arguments);
        if (fn.args.length < orig_func.length) {
          return fn;
        } else {
          return orig_func.apply(this, fn.args);
        }
      };
      return function() {
        fn.args = ap.slice.call(args, 1);
        return fn.apply(this, arguments);
      };
    };

    Util.readServerJSFile = function(filepath, callback) {
      return $.ajax({
        url: filepath,
        type: 'GET',
        dataType: 'script',
        success: callback
      });
    };

    Util.readServerTextFile = function(filepath, callback) {
      return $.ajax({
        url: filepath,
        type: 'GET',
        dataType: 'text',
        success: callback
      });
    };

    Util.splitlines = function(s) {
      return s.split(/\r\n|[\n\r]/);
    };

    return Util;

  })();

  window.Util = Util;

}).call(this);
